ACCUMBENS_LEFT = "CIFTI_STRUCTURE_ACCUMBENS_LEFT"
ACCUMBENS_RIGHT = "CIFTI_STRUCTURE_ACCUMBENS_RIGHT"
ALL_WHITE_MATTER = "CIFTI_STRUCTURE_ALL_WHITE_MATTER"
ALL_GREY_MATTER = "CIFTI_STRUCTURE_ALL_GREY_MATTER"
AMYGDALA_LEFT = "CIFTI_STRUCTURE_AMYGDALA_LEFT"
AMYGDALA_RIGHT = "CIFTI_STRUCTURE_AMYGDALA_RIGHT"
BRAIN_STEM = "CIFTI_STRUCTURE_BRAIN_STEM"
CAUDATE_LEFT = "CIFTI_STRUCTURE_CAUDATE_LEFT"
CAUDATE_RIGHT = "CIFTI_STRUCTURE_CAUDATE_RIGHT"
CEREBELLAR_WHITE_MATTER_LEFT = "CIFTI_STRUCTURE_CEREBELLAR_WHITE_MATTER_LEFT"
CEREBELLAR_WHITE_MATTER_RIGHT = "CIFTI_STRUCTURE_CEREBELLAR_WHITE_MATTER_RIGHT"
CEREBELLUM = "CIFTI_STRUCTURE_CEREBELLUM"
CEREBELLUM_LEFT = "CIFTI_STRUCTURE_CEREBELLUM_LEFT"
CEREBELLUM_RIGHT = "CIFTI_STRUCTURE_CEREBELLUM_RIGHT"
CEREBRAL_WHITE_MATTER_LEFT = "CIFTI_STRUCTURE_CEREBRAL_WHITE_MATTER_LEFT"
CEREBRAL_WHITE_MATTER_RIGHT = "CIFTI_STRUCTURE_CEREBRAL_WHITE_MATTER_RIGHT"
CORTEX = "CIFTI_STRUCTURE_CORTEX"
CORTEX_LEFT = "CIFTI_STRUCTURE_CORTEX_LEFT"
CORTEX_RIGHT = "CIFTI_STRUCTURE_CORTEX_RIGHT"
DIENCEPHALON_VENTRAL_LEFT = "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_LEFT"
DIENCEPHALON_VENTRAL_RIGHT = "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_RIGHT"
HIPPOCAMPUS_LEFT = "CIFTI_STRUCTURE_HIPPOCAMPUS_LEFT"
HIPPOCAMPUS_RIGHT = "CIFTI_STRUCTURE_HIPPOCAMPUS_RIGHT"
OTHER = "CIFTI_STRUCTURE_OTHER"
OTHER_GREY_MATTER = "CIFTI_STRUCTURE_OTHER_GREY_MATTER"
OTHER_WHITE_MATTER = "CIFTI_STRUCTURE_OTHER_WHITE_MATTER"
PALLIDUM_LEFT = "CIFTI_STRUCTURE_PALLIDUM_LEFT"
PALLIDUM_RIGHT = "CIFTI_STRUCTURE_PALLIDUM_RIGHT"
PUTAMEN_LEFT = "CIFTI_STRUCTURE_PUTAMEN_LEFT"
PUTAMEN_RIGHT = "CIFTI_STRUCTURE_PUTAMEN_RIGHT"
THALAMUS_LEFT = "CIFTI_STRUCTURE_THALAMUS_LEFT"
THALAMUS_RIGHT = "CIFTI_STRUCTURE_THALAMUS_RIGHT"

STRUCTURES = ["CIFTI_STRUCTURE_ACCUMBENS_LEFT",
              "CIFTI_STRUCTURE_ACCUMBENS_RIGHT",
              "CIFTI_STRUCTURE_ALL_WHITE_MATTER",
              "CIFTI_STRUCTURE_ALL_GREY_MATTER",
              "CIFTI_STRUCTURE_AMYGDALA_LEFT",
              "CIFTI_STRUCTURE_AMYGDALA_RIGHT",
              "CIFTI_STRUCTURE_BRAIN_STEM",
              "CIFTI_STRUCTURE_CAUDATE_LEFT",
              "CIFTI_STRUCTURE_CAUDATE_RIGHT",
              "CIFTI_STRUCTURE_CEREBELLAR_WHITE_MATTER_LEFT",
              "CIFTI_STRUCTURE_CEREBELLAR_WHITE_MATTER_RIGHT",
              "CIFTI_STRUCTURE_CEREBELLUM",
              "CIFTI_STRUCTURE_CEREBELLUM_LEFT",
              "CIFTI_STRUCTURE_CEREBELLUM_RIGHT",
              "CIFTI_STRUCTURE_CEREBRAL_WHITE_MATTER_LEFT",
              "CIFTI_STRUCTURE_CEREBRAL_WHITE_MATTER_RIGHT",
              "CIFTI_STRUCTURE_CORTEX",
              "CIFTI_STRUCTURE_CORTEX_LEFT",
              "CIFTI_STRUCTURE_CORTEX_RIGHT",
              "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_LEFT",
              "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_RIGHT",
              "CIFTI_STRUCTURE_HIPPOCAMPUS_LEFT",
              "CIFTI_STRUCTURE_HIPPOCAMPUS_RIGHT",
              "CIFTI_STRUCTURE_OTHER",
              "CIFTI_STRUCTURE_OTHER_GREY_MATTER",
              "CIFTI_STRUCTURE_OTHER_WHITE_MATTER",
              "CIFTI_STRUCTURE_PALLIDUM_LEFT",
              "CIFTI_STRUCTURE_PALLIDUM_RIGHT",
              "CIFTI_STRUCTURE_PUTAMEN_LEFT",
              "CIFTI_STRUCTURE_PUTAMEN_RIGHT",
              "CIFTI_STRUCTURE_THALAMUS_LEFT",
              "CIFTI_STRUCTURE_THALAMUS_RIGHT"]
